import { createFileRoute } from "@tanstack/react-router";
import { LegalPage, H2 } from "@/components/legal-page";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — CoFund" },
      { name: "description", content: "How CoFund collects, uses and protects your personal information." },
    ],
  }),
  component: () => (
    <LegalPage eyebrow="Legal" title="Privacy Policy" intro="How we collect, use and protect your information.">
      <H2>1. Information we collect</H2>
      <p>We collect information you provide directly (account, KYC, business documents), information generated by your use of CoFund (activity, posts, transactions), and information from third parties used for verification.</p>
      <H2>2. How we use your information</H2>
      <p>To operate CoFund, verify identities and businesses, process investments via escrow partners, detect fraud, and improve the platform.</p>
      <H2>3. Sharing</H2>
      <p>We share data with banking and escrow partners, KYC providers, and authorities where legally required. We never sell your personal data.</p>
      <H2>4. Your rights</H2>
      <p>You may access, update, export or delete your data at any time from your profile. Contact <a className="text-primary" href="mailto:privacy@cofund.africa">privacy@cofund.africa</a>.</p>
      <H2>5. Security</H2>
      <p>We use industry-standard encryption in transit and at rest, with strict access controls. No system is perfectly secure — review our Trust Centre for details.</p>
    </LegalPage>
  ),
});