/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as EscrowRouteImport } from './routes/escrow'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSuitabilityRouteImport } from './routes/_authenticated/suitability'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyBusinessRouteImport } from './routes/_authenticated/my-business'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedUsersUsernameRouteImport } from './routes/_authenticated/users/$username'
import { Route as AuthenticatedOfferingsOpportunityIdRouteImport } from './routes/_authenticated/offerings/$opportunityId'
import { Route as AuthenticatedInvestOpportunityIdRouteImport } from './routes/_authenticated/invest/$opportunityId'
import { Route as AuthenticatedBusinessSlugRouteImport } from './routes/_authenticated/business/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowRoute = EscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuitabilityRoute =
  AuthenticatedSuitabilityRouteImport.update({
    id: '/suitability',
    path: '/suitability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyBusinessRoute = AuthenticatedMyBusinessRouteImport.update({
  id: '/my-business',
  path: '/my-business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersUsernameRoute =
  AuthenticatedUsersUsernameRouteImport.update({
    id: '/users/$username',
    path: '/users/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfferingsOpportunityIdRoute =
  AuthenticatedOfferingsOpportunityIdRouteImport.update({
    id: '/offerings/$opportunityId',
    path: '/offerings/$opportunityId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestOpportunityIdRoute =
  AuthenticatedInvestOpportunityIdRouteImport.update({
    id: '/invest/$opportunityId',
    path: '/invest/$opportunityId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessSlugRoute =
  AuthenticatedBusinessSlugRouteImport.update({
    id: '/business/$slug',
    path: '/business/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/escrow': typeof EscrowRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/risk': typeof RiskRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/home': typeof AuthenticatedHomeRoute
  '/my-business': typeof AuthenticatedMyBusinessRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suitability': typeof AuthenticatedSuitabilityRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/business/$slug': typeof AuthenticatedBusinessSlugRoute
  '/invest/$opportunityId': typeof AuthenticatedInvestOpportunityIdRoute
  '/offerings/$opportunityId': typeof AuthenticatedOfferingsOpportunityIdRoute
  '/users/$username': typeof AuthenticatedUsersUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/escrow': typeof EscrowRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/risk': typeof RiskRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/home': typeof AuthenticatedHomeRoute
  '/my-business': typeof AuthenticatedMyBusinessRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suitability': typeof AuthenticatedSuitabilityRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/business/$slug': typeof AuthenticatedBusinessSlugRoute
  '/invest/$opportunityId': typeof AuthenticatedInvestOpportunityIdRoute
  '/offerings/$opportunityId': typeof AuthenticatedOfferingsOpportunityIdRoute
  '/users/$username': typeof AuthenticatedUsersUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/escrow': typeof EscrowRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/risk': typeof RiskRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/my-business': typeof AuthenticatedMyBusinessRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suitability': typeof AuthenticatedSuitabilityRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/business/$slug': typeof AuthenticatedBusinessSlugRoute
  '/_authenticated/invest/$opportunityId': typeof AuthenticatedInvestOpportunityIdRoute
  '/_authenticated/offerings/$opportunityId': typeof AuthenticatedOfferingsOpportunityIdRoute
  '/_authenticated/users/$username': typeof AuthenticatedUsersUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/escrow'
    | '/how-it-works'
    | '/onboarding'
    | '/privacy'
    | '/risk'
    | '/terms'
    | '/admin'
    | '/browse'
    | '/community'
    | '/home'
    | '/my-business'
    | '/notifications'
    | '/portfolio'
    | '/profile'
    | '/security'
    | '/settings'
    | '/suitability'
    | '/wallet'
    | '/business/$slug'
    | '/invest/$opportunityId'
    | '/offerings/$opportunityId'
    | '/users/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/escrow'
    | '/how-it-works'
    | '/onboarding'
    | '/privacy'
    | '/risk'
    | '/terms'
    | '/admin'
    | '/browse'
    | '/community'
    | '/home'
    | '/my-business'
    | '/notifications'
    | '/portfolio'
    | '/profile'
    | '/security'
    | '/settings'
    | '/suitability'
    | '/wallet'
    | '/business/$slug'
    | '/invest/$opportunityId'
    | '/offerings/$opportunityId'
    | '/users/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/escrow'
    | '/how-it-works'
    | '/onboarding'
    | '/privacy'
    | '/risk'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/browse'
    | '/_authenticated/community'
    | '/_authenticated/home'
    | '/_authenticated/my-business'
    | '/_authenticated/notifications'
    | '/_authenticated/portfolio'
    | '/_authenticated/profile'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/suitability'
    | '/_authenticated/wallet'
    | '/_authenticated/business/$slug'
    | '/_authenticated/invest/$opportunityId'
    | '/_authenticated/offerings/$opportunityId'
    | '/_authenticated/users/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EscrowRoute: typeof EscrowRoute
  HowItWorksRoute: typeof HowItWorksRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RiskRoute: typeof RiskRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrow': {
      id: '/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof EscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suitability': {
      id: '/_authenticated/suitability'
      path: '/suitability'
      fullPath: '/suitability'
      preLoaderRoute: typeof AuthenticatedSuitabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-business': {
      id: '/_authenticated/my-business'
      path: '/my-business'
      fullPath: '/my-business'
      preLoaderRoute: typeof AuthenticatedMyBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$username': {
      id: '/_authenticated/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof AuthenticatedUsersUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offerings/$opportunityId': {
      id: '/_authenticated/offerings/$opportunityId'
      path: '/offerings/$opportunityId'
      fullPath: '/offerings/$opportunityId'
      preLoaderRoute: typeof AuthenticatedOfferingsOpportunityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invest/$opportunityId': {
      id: '/_authenticated/invest/$opportunityId'
      path: '/invest/$opportunityId'
      fullPath: '/invest/$opportunityId'
      preLoaderRoute: typeof AuthenticatedInvestOpportunityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/$slug': {
      id: '/_authenticated/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof AuthenticatedBusinessSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMyBusinessRoute: typeof AuthenticatedMyBusinessRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuitabilityRoute: typeof AuthenticatedSuitabilityRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedBusinessSlugRoute: typeof AuthenticatedBusinessSlugRoute
  AuthenticatedInvestOpportunityIdRoute: typeof AuthenticatedInvestOpportunityIdRoute
  AuthenticatedOfferingsOpportunityIdRoute: typeof AuthenticatedOfferingsOpportunityIdRoute
  AuthenticatedUsersUsernameRoute: typeof AuthenticatedUsersUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMyBusinessRoute: AuthenticatedMyBusinessRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuitabilityRoute: AuthenticatedSuitabilityRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedBusinessSlugRoute: AuthenticatedBusinessSlugRoute,
  AuthenticatedInvestOpportunityIdRoute: AuthenticatedInvestOpportunityIdRoute,
  AuthenticatedOfferingsOpportunityIdRoute:
    AuthenticatedOfferingsOpportunityIdRoute,
  AuthenticatedUsersUsernameRoute: AuthenticatedUsersUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EscrowRoute: EscrowRoute,
  HowItWorksRoute: HowItWorksRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RiskRoute: RiskRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
